// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpXZziCM9Ux-QOSEr4Wg8xZCrFyvVlej4',
    appId: '1:475230642075:web:5c7a58d394844ea734cb3e',
    messagingSenderId: '475230642075',
    projectId: 'stacked-mvvm',
    authDomain: 'stacked-mvvm.firebaseapp.com',
    storageBucket: 'stacked-mvvm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuqCGno32yx3QU3bTxVE1WJwBzeVEGjbs',
    appId: '1:475230642075:android:736c1181ec4549b634cb3e',
    messagingSenderId: '475230642075',
    projectId: 'stacked-mvvm',
    storageBucket: 'stacked-mvvm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdCEp_qXQe5btIZQF1iqeh4l6nJ3-ellM',
    appId: '1:475230642075:ios:8c937cff7de8287134cb3e',
    messagingSenderId: '475230642075',
    projectId: 'stacked-mvvm',
    storageBucket: 'stacked-mvvm.appspot.com',
    iosClientId: '475230642075-kmclru1idiaeprmb2n441p70i7jm5njh.apps.googleusercontent.com',
    iosBundleId: 'com.example.stackedMvvmFirebase',
  );
}
